export const PROYECTOS = [
  {
    numero: 1, titulo: 'Calculadora de Promedio',
    descripcion: 'Herramienta web para el cálculo de promedio ponderado de notas académicas. Permite ingresar calificaciones con distintos pesos y obtener el promedio final de forma inmediata. Desarrollada con HTML, CSS y JavaScript puro.',
    tech_label: 'Proyecto 1 · JavaScript',
    url_vercel: 'https://calculadora-de-promedio-kappa.vercel.app/', url_github: null,
  },
  {
    numero: 2, titulo: 'Convertidor de Temperatura',
    descripcion: 'Aplicación web para convertir entre unidades de temperatura: Celsius, Fahrenheit y Kelvin. Interfaz limpia y cálculo instantáneo. Útil para ejercicios de termodinámica y balance de energía en ingeniería ambiental.',
    tech_label: 'Proyecto 2 · JavaScript',
    url_vercel: 'https://convertidor-de-temperatura-seven.vercel.app/', url_github: null,
  },
  {
    numero: 3, titulo: 'Mi Closet — Closet Virtual',
    descripcion: 'App web full-stack para gestionar un armario virtual. Subí fotos de tu ropa, filtrá por categoría, marcá favoritos, registrá cuántas veces usaste cada prenda y armá outfits combinando prendas. Usa Vercel Postgres (SQL) para los datos y Vercel Blob para las imágenes.',
    tech_label: 'Proyecto 3 · Next.js · TypeScript · SQL',
    url_vercel: 'https://mi-closet.vercel.app', url_github: 'https://github.com/QueMsDa/closet-virtual',
  },
  {
    numero: 4, titulo: 'MusicHome — Música en Google Home',
    descripcion: 'App web + servicio Windows para subir música personal a la nube y transmitirla a un Google Home sin necesitar Spotify. Lee metadatos ID3 automáticamente, controla el volumen en tiempo real y persiste la cola entre reinicios. Integración con IFTTT para comandos de voz.',
    tech_label: 'Proyecto 4 · Next.js · TypeScript · Redis',
    url_vercel: 'https://music-home-beta.vercel.app', url_github: 'https://github.com/QueMsDa/music-home',
  },
  {
    numero: 5, titulo: 'Mis Mapas — Dispersión de Contaminantes',
    descripcion: 'App web full-stack para registrar y visualizar la dispersión de contaminantes atmosféricos (PM2.5 y PM10) usando el modelo de pluma gaussiana de Pfeiffer. Hacé clic en el mapa para fijar el punto de emisión, ingresá las mediciones y el heatmap se actualiza en tiempo real con los datos de todos los registros. Usa Vercel Postgres (SQL) para el historial persistente.',
    tech_label: 'Proyecto 5 · Next.js · TypeScript · SQL · Leaflet',
    url_vercel: 'https://mis-mapas.vercel.app', url_github: 'https://github.com/QueMsDa/mis-mapas',
  },
  {
    numero: 6, titulo: 'CromaLab — Análisis de Cromatogramas',
    descripcion: 'App web full-stack para analizar cromatogramas de papel de Pfeiffer. Subí una foto del cromatograma de suelo y el sistema divide la imagen en zonas radiales, interpreta los colores (materia orgánica, actividad biológica, minerales) y genera un diagnóstico con puntaje y recomendaciones. Usa Vercel Postgres (SQL) para el historial y Vercel Blob para las imágenes. Sin IA externa.',
    tech_label: 'Proyecto 6 · Next.js · TypeScript · SQL · Sharp',
    url_vercel: 'https://cromalab-indol.vercel.app', url_github: 'https://github.com/QueMsDa/cromas-analisis',
  },
  {
    numero: 7, titulo: 'Finanzas Personal — App Android + Cloud',
    descripcion: 'App Android nativa (Kotlin + Jetpack Compose) para análisis financiero personal en tiempo real. Registra gastos manualmente o importándolos desde capturas de pantalla de Yape mediante OCR (Google ML Kit). Base de datos cloud con Supabase PostgreSQL y sincronización automática con Google Sheets y Excel. Sin IA para el análisis, solo datos reales.',
    tech_label: 'Proyecto 7 · Android · Kotlin · Supabase · ML Kit',
    url_vercel: null, url_github: 'https://github.com/QueMsDa/finanzas-personales',
  },
];

export const CURSOS = [
  {
    slug: 'hidrologia', nombre: 'Hidrología', icon: '◈', tiene_unidades: true, orden: 1,
    eyebrow: 'Portafolio de Curso · UAC',
    lead: 'Ciclo hidrológico, gestión de cuencas, Ley 29338, modelamiento con HEC-HMS y análisis de caudales. Selecciona una unidad para explorar su contenido.',
    secciones: [
      {
        slug: 'unidad-1', numero: 'I', bubble_label: 'Unidad 1', bubble_title: 'Agua, Derecho y Cuencas',
        titulo: 'Unidad 1 — Agua, Derecho y Cuencas',
        subtitulo: 'El agua en el mundo, situación en Perú, Ley 29338 y sistemas de cuencas hidrográficas',
        num_style: null, orden: 1,
        temas: [
          { label: 'Tema 1.1', titulo: 'El Agua en el Mundo', pill: null, orden: 1,
            descripcion: 'Distribución global del agua, ciclo hidrológico y disponibilidad por regiones. Escasez hídrica como desafío para la sostenibilidad del siglo XXI.',
            docs: [{ nombre: 'El agua en el mundo (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/El%20agua%20en%20el%20mundo.pdf', disponible: false }] },
          { label: 'Tema 1.2', titulo: 'Agua en Perú y Estrés Hídrico', pill: null, orden: 2,
            descripcion: 'Situación hídrica del Perú, distribución espacial del recurso y zonas de estrés hídrico. Brecha entre disponibilidad y demanda en la región andina.',
            docs: [
              { nombre: 'Agua en Perú (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/El%20agua%20en%20el%20peru.pdf', disponible: false },
              { nombre: 'Estrés hídrico (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/ESTRES%20HIDRICO%20EN%20EL%20PERU.pdf', disponible: false },
            ] },
          { label: 'Tema 1.3 · Marco legal', titulo: 'Ley 29338 — Ley de Recursos Hídricos', pill: null, orden: 3,
            descripcion: 'Marco normativo nacional del agua en Perú. Principios, derechos de uso, autoridades competentes y regímenes de licencias. Base legal para cualquier proyecto hídrico.',
            docs: [{ nombre: 'Ley 29338 (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/LEY%2029338%20Ley%20de%20los%20recursos%20hidricos.pdf', disponible: false }] },
          { label: 'Tema 1.4', titulo: 'Cuencas Hidrográficas y Licencias de Uso', pill: null, orden: 4,
            descripcion: 'Delimitación y caracterización de cuencas, regímenes hidrológicos y tipos de licencias de uso de agua en el marco de la legislación peruana.',
            docs: [{ nombre: 'Cuencas y licencias (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/cuencas%20y%20licencias.pdf', disponible: false }] },
          { label: 'Tema 1.5 · Reflexión', titulo: 'Pluralismo Legal y Gestión del Agua', pill: null, orden: 5,
            descripcion: 'Coexistencia de sistemas legales formales e informales en la gestión del agua. Conflictos entre derecho positivo y usos consuetudinarios en comunidades andinas.',
            docs: [{ nombre: 'Pluralismo legal (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/Pluralismo%20legal%20y%20gestion%20del%20agua.pdf', disponible: false }] },
          { label: 'IF · Portafolio U1', titulo: 'Investigación Formativa — Unidad 1', pill: null, orden: 6,
            descripcion: 'Portafolio de la primera unidad: compilación de aprendizajes, reflexiones y evidencias sobre el recurso hídrico y su marco normativo en Perú.',
            docs: [{ nombre: 'Portafolio U1 (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%201/PORTAFOLIO%20U1.pdf', disponible: false }] },
        ],
      },
      {
        slug: 'unidad-2', numero: 'II', bubble_label: 'Unidad 2', bubble_title: 'GIRH y Parámetros Morfométricos',
        titulo: 'Unidad 2 — GIRH y Parámetros Morfométricos',
        subtitulo: 'Gestión integrada, calidad del agua, adaptación climática y caracterización de cuencas',
        num_style: null, orden: 2,
        temas: [
          { label: 'Tema 2.1', titulo: 'Gestión Integrada de Recursos Hídricos', pill: null, orden: 1,
            descripcion: 'Enfoque GIRH: coordinación entre usos del agua, actores institucionales y planificación a escala de cuenca. Principios de Dublín y gobernanza del agua.',
            docs: [{ nombre: 'GIRH (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%202/GIRH.pdf', disponible: false }] },
          { label: 'Tema 2.2', titulo: 'Calidad del Agua', pill: null, orden: 2,
            descripcion: 'Parámetros fisicoquímicos y biológicos. Estándares de calidad ambiental (ECA) para agua en Perú. Índices de calidad y protocolos de monitoreo.',
            docs: [{ nombre: 'Calidad del agua (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%202/Calidad%20del%20agua.pdf', disponible: false }] },
          { label: 'Tema 2.3', titulo: 'Adaptación al Cambio Climático', pill: null, orden: 3,
            descripcion: 'Estrategias de adaptación para sistemas hídricos frente a variabilidad climática. Reducción de vulnerabilidad en cuencas andinas con glaciares en retroceso.',
            docs: [{ nombre: 'Adaptación climática (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%202/Adaptacion%20climatica.pdf', disponible: false }] },
          { label: 'Tema 2.4 · Normativa', titulo: 'Normas Sectoriales del Agua', pill: null, orden: 4,
            descripcion: 'Regulaciones sectoriales complementarias a la Ley 29338: minería, agricultura, uso poblacional. Interacción entre MINAM, ANA y gobiernos regionales.',
            docs: [{ nombre: 'Normas sectoriales (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%202/Normas%20Sectoriales.pdf', disponible: false }] },
          { label: 'Tema 2.5 · SIG', titulo: 'Parámetros Morfométricos de Cuencas', pill: null, orden: 5,
            descripcion: 'Cálculo de forma, relieve y red hidrográfica con ArcGIS. Índices de Gravelius, factor de forma, densidad de drenaje y tiempo de concentración.',
            docs: [{ nombre: 'Parámetros morfométricos (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%202/parametros%20morfometricos.pdf', disponible: true }] },
          { label: 'IF · Portafolio U2', titulo: 'Investigación Formativa — Unidad 2', pill: null, orden: 6,
            descripcion: 'Portafolio de la segunda unidad: evidencias de la caracterización morfométrica de cuencas y reflexiones sobre gestión integrada del recurso hídrico.',
            docs: [{ nombre: 'IF Cuenca U2 (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%202/IF%20CUENCA%20U2.pdf', disponible: true }] },
        ],
      },
      {
        slug: 'unidad-3', numero: 'III', bubble_label: 'Unidad 3', bubble_title: 'Escorrentía y Modelamiento',
        titulo: 'Unidad 3 — Escorrentía y Modelamiento Hidrológico',
        subtitulo: 'Sequías, HEC-HMS, balance hídrico P=ET+Q+ΔS, caudales con Manning y fenómeno ENSO',
        num_style: null, orden: 3,
        temas: [
          { label: 'Tema 3.1', titulo: 'Sequías — Tipos y Gestión', pill: null, orden: 1,
            descripcion: 'Clasificación de sequías: meteorológica, hidrológica, agrícola y socioeconómica. Índices SPI y PDSI y estrategias de respuesta temprana.',
            docs: [{ nombre: 'Sequías (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/Sequias.pdf', disponible: true }] },
          { label: 'Tema 3.2', titulo: 'Escorrentía Superficial', pill: null, orden: 2,
            descripcion: 'Génesis de la escorrentía, número de curva CN del SCS, hietogramas de diseño y separación de flujo base. Caudales pico para distintos periodos de retorno.',
            docs: [{ nombre: 'Escorrentía (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/Escorrentia.pdf', disponible: true }] },
          { label: 'Tema 3.3 · Trabajo', titulo: 'Trabajo Integrador', pill: null, orden: 3,
            descripcion: 'Aplicación integrada de los conceptos de la unidad: caracterización de cuenca, modelamiento de eventos lluvia-escorrentía y análisis de resultados.',
            docs: [{ nombre: 'Trabajo integrador (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/Trabajo%20integrador.pdf', disponible: true }] },
          { label: 'Tema 3.4 · HEC-HMS · Grupo 4', titulo: 'Modelamiento HEC-HMS — Cuenca Chontali', pill: null, orden: 4,
            descripcion: 'Configuración del modelo HEC-HMS para la cuenca Chontali: parámetros morfométricos, calibración y simulación de hidrogramas de crecida.',
            docs: [{ nombre: 'HEC-HMS Chontali (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/HEC-HMS%20Cuenca%20Chontali%20Grupo%204.pdf', disponible: true }] },
          { label: 'Tema 3.5 · Ecuación', titulo: 'Balance Hídrico — P = ET + Q + ΔS', pill: null, orden: 5,
            descripcion: 'Aplicación de la ecuación de balance a escala de cuenca. Estimación de evapotranspiración real con métodos Penman-Monteith y Hargreaves.',
            docs: [{ nombre: 'Balance hídrico (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/balance%20hidrico.pdf', disponible: false }] },
          { label: 'Tema 3.6 · Hidráulica', titulo: 'Caudales y Fórmula de Manning', pill: null, orden: 6,
            descripcion: 'Cálculo de caudal en canales y cauces naturales mediante la ecuación de Manning. Rugosidad, sección hidráulica y pendiente de la lámina de agua.',
            docs: [{ nombre: 'Caudales y Manning (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/caudales%20y%20manning.pdf', disponible: false }] },
          { label: 'Tema 3.7 · Software', titulo: 'Modelamiento Hidrológico con SIG', pill: null, orden: 7,
            descripcion: 'Integración de ArcGIS y modelos hidrológicos para la simulación de eventos extremos. ArcGIS Hydrology Toolset para extracción de parámetros de cuenca.',
            docs: [{ nombre: 'Modelamiento (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/modelamiento%20hidrologico.pdf', disponible: false }] },
          { label: 'Tema 3.8 · Climatología', titulo: 'Fenómeno ENSO', pill: null, orden: 8,
            descripcion: 'El Niño-Oscilación del Sur: mecanismos de teleconexión, impacto en la hidrología del Perú y gestión de riesgo de inundaciones y sequías asociadas.',
            docs: [{ nombre: 'Fenómeno ENSO (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/ENSO.pdf', disponible: false }] },
          { label: 'Opinión · Columnas', titulo: 'Columnas de Opinión', pill: null, orden: 9,
            descripcion: 'Reflexiones sobre problemáticas hídricas actuales: escasez, cambio climático y gobernanza del agua en el contexto andino peruano.',
            docs: [{ nombre: 'Columnas (PDF)', url: '/assets/documentos%20de%20hidrologia/unidad%203/columnas%20de%20opinion.pdf', disponible: false }] },
        ],
      },
      {
        slug: 'laboratorio', numero: 'Lab', bubble_label: 'Laboratorio', bubble_title: 'Prácticas de Análisis',
        titulo: 'Laboratorio — Prácticas de Hidrología',
        subtitulo: 'Medición de caudales, análisis de calidad de agua y caracterización de sedimentos en condiciones controladas',
        num_style: 'font-size:1.55rem', orden: 4,
        temas: [
          { label: 'Práctica 1', titulo: 'Aforo de Caudales con Molinete', pill: null, orden: 1,
            descripcion: 'Medición de caudal por el método velocidad-área. Uso de molinete hidrométrico, selección de secciones transversales y cálculo de gasto hídrico a partir de perfiles de velocidad.',
            docs: [{ nombre: 'Informe Lab 1 (PDF)', url: '#', disponible: false }] },
          { label: 'Práctica 2', titulo: 'Parámetros Fisicoquímicos del Agua', pill: null, orden: 2,
            descripcion: 'Determinación de pH, turbidez, conductividad eléctrica, oxígeno disuelto y temperatura. Comparación con los Estándares de Calidad Ambiental (ECA) para agua según normativa peruana.',
            docs: [{ nombre: 'Informe Lab 2 (PDF)', url: '#', disponible: false }] },
          { label: 'Práctica 3', titulo: 'Análisis Granulométrico y Permeabilidad', pill: null, orden: 3,
            descripcion: 'Granulometría de sedimentos fluviales por tamizado. Ensayo de permeabilidad de Darcy para suelos no cohesivos. Relación entre textura del suelo e infiltración.',
            docs: [{ nombre: 'Informe Lab 3 (PDF)', url: '#', disponible: false }] },
          { label: 'IF · Compilado Lab', titulo: 'Informe Integrador de Laboratorio', pill: null, orden: 4,
            descripcion: 'Compilación y análisis de los resultados obtenidos en las tres prácticas. Reflexión crítica sobre la relación entre mediciones de laboratorio y comportamiento real de cuencas.',
            docs: [{ nombre: 'Informe Integrador (PDF)', url: '#', disponible: false }] },
        ],
      },
      {
        slug: 'salida-campo', numero: 'SC', bubble_label: 'Salida de Campo', bubble_title: 'Trabajo en Cuenca',
        titulo: 'Salida de Campo — Trabajo en Cuenca',
        subtitulo: 'Reconocimiento in situ, aforo en campo, muestreo de agua y registro fotográfico en la cuenca de estudio',
        num_style: 'font-size:1.45rem', orden: 5,
        temas: [
          { label: 'Actividad 1 · Reconocimiento', titulo: 'Reconocimiento de Cuenca Hidrográfica', pill: null, orden: 1,
            descripcion: 'Identificación de la red de drenaje, puntos de muestreo, obras hidráulicas y zonas de recarga. Contraste entre la cartografía previa (ArcGIS) y las condiciones reales del terreno.',
            docs: [{ nombre: 'Ficha de reconocimiento (PDF)', url: '#', disponible: false }] },
          { label: 'Actividad 2 · Aforo', titulo: 'Aforo In Situ — Método del Flotador', pill: null, orden: 2,
            descripcion: 'Estimación de caudal en campo mediante el método del flotador y sección transversal. Registro de nivel de agua y velocidad superficial. Comparación con registros históricos de la estación.',
            docs: [{ nombre: 'Datos de aforo (PDF)', url: '#', disponible: false }] },
          { label: 'Actividad 3 · Muestreo', titulo: 'Muestreo y Registro de Parámetros', pill: null, orden: 3,
            descripcion: 'Toma de muestras de agua superficial en puntos estratégicos de la cuenca. Medición de parámetros in situ con multiparámetro portátil: pH, OD, conductividad y temperatura.',
            docs: [{ nombre: 'Ficha de muestreo (PDF)', url: '#', disponible: false }] },
          { label: 'IF · Informe Final', titulo: 'Informe Final de Salida de Campo', pill: null, orden: 4,
            descripcion: 'Documento integrador con descripción del área de estudio, metodología aplicada, resultados de aforo y muestreo, análisis comparativo y conclusiones sobre el estado hídrico de la cuenca.',
            docs: [{ nombre: 'Informe de campo (PDF)', url: '#', disponible: false }] },
        ],
      },
    ],
  },
  {
    slug: 'tecnologias-limpias', nombre: 'Tecnologías Limpias', icon: '◇', tiene_unidades: true, orden: 2,
    eyebrow: 'Portafolio de Curso · UAC',
    lead: 'PML, diagramas de proceso, ACV, balances de materia y energía, análisis PINCH e ISO 50001. Selecciona una unidad para explorar su contenido.',
    secciones: [
      {
        slug: 'unidad-1', numero: 'I', bubble_label: 'Unidad 1', bubble_title: 'PML, PFDs y ACV',
        titulo: 'Unidad 1 — PML, PFDs y ACV',
        subtitulo: 'Tecnologías limpias, diagramas de proceso, análisis de ciclo de vida y responsabilidad social',
        num_style: null, orden: 1,
        temas: [
          { label: 'PL1', titulo: 'Introducción a las Tecnologías Limpias', pill: null, orden: 1,
            descripcion: 'La PML como respuesta sistémica a los impactos industriales. Estrategias preventivas frente al enfoque reactivo de tratamiento de residuos al final del proceso.',
            docs: [{ nombre: 'Apuntes PL1 (PPTX)', url: '/assets/Documentos/apuntes-Tecnologias/PL1.pptx', disponible: true }] },
          { label: 'PL1 · Línea de tiempo · Grupo 4', titulo: 'Evolución Histórica de las Tecnologías Limpias', pill: null, orden: 2,
            descripcion: 'Del movimiento ambiental de los 70 hasta las normas ISO actuales. Hitos regulatorios y tecnológicos clave en la historia de la gestión ambiental industrial.',
            docs: [{ nombre: 'Línea de tiempo (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Linea%20del%20tiempo%20Qu%C3%ADmica%20y%20Petroqu%C3%ADmi.pdf', disponible: true }] },
          { label: 'PL2', titulo: 'Procesos Industriales y Medio Ambiente', pill: null, orden: 3,
            descripcion: 'Interacción entre procesos productivos y ecosistemas. Flujos de materiales, generación de residuos y oportunidades de cierre de ciclos en la industria.',
            docs: [{ nombre: 'Apuntes PL2 (PPTX)', url: '/assets/Documentos/apuntes-Tecnologias/PL2%2026.pptx', disponible: true }] },
          { label: 'PL3 · Norma', titulo: 'Diagramas de Flujo de Procesos — ISO 10628', pill: null, orden: 4,
            descripcion: 'PFDs y P&IDs para visualizar el flujo de materia y energía, identificar cuellos de botella y documentar procesos con estándares internacionales.',
            docs: [
              { nombre: 'Apuntes PL3 (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/PL3.1.pdf', disponible: true },
              { nombre: 'ISO 10628 (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/543642075-Norma-ISO-10628-Para-Diagramas-de-Procesos.pdf', disponible: true },
            ] },
          { label: 'PL4', titulo: 'Análisis del Ciclo de Vida (ACV)', pill: null, orden: 5,
            descripcion: 'Cuantificación de impactos desde la cuna hasta la tumba: límites del sistema, inventario de ciclo de vida y evaluación de impacto ambiental (calentamiento global, eutrofización…).',
            docs: [{ nombre: 'Apuntes PL4 (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/PL4.pdf', disponible: true }] },
          { label: 'PL5', titulo: 'Producción Más Limpia — Enfoque Preventivo', pill: null, orden: 6,
            descripcion: 'Ajuste de parámetros de proceso, recuperación de solventes y sustitución de insumos peligrosos. Integración de PML con normas y políticas públicas.',
            docs: [{ nombre: 'Lectura PML (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Lectura%20PML.pdf', disponible: true }] },
          { label: 'Taller 1 · Grupo 4', titulo: 'Producción de Lubricantes', pill: null, orden: 7,
            descripcion: 'Diagnóstico del proceso: mapeo de consumo energético, localización de fugas y cuantificación de pérdidas. Propuesta de recuperación de calor y mantenimiento predictivo.',
            docs: [{ nombre: 'Taller 1 — Grupo 4 (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/grupo 4 taller 1.pdf', disponible: true }] },
          { label: 'Taller 2 · Grupo 4', titulo: 'Diagrama de Flujo — Flexicoking', pill: null, orden: 8,
            descripcion: 'Tecnologías que transforman residuos pesados en productos valiosos. Balances energéticos y evaluación de emisiones H₂S y CO₂ en procesos de refinería.',
            docs: [{ nombre: 'Flexicoking (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Diagrama de flujo Flexicoking-comprimido.pdf', disponible: true }] },
          { label: 'IF · Investigación Formativa U1', titulo: 'ACV Comparativo — Textiles Perú vs China', pill: null, orden: 9,
            descripcion: 'Análisis comparativo de ciclo de vida de prendas: producción de algodón en Perú frente a manufactura en China. Propuestas de mejora con impacto cuantificado.',
            docs: [{ nombre: 'IF TEC (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/IF%20TEC.pdf', disponible: true }] },
          { label: 'Responsabilidad Social', titulo: 'RS 1 — Tecnologías Limpias', pill: null, orden: 10,
            descripcion: 'Las empresas deben asumir responsabilidad frente a la comunidad integrando sostenibilidad en su gestión. PML como compromiso ambiental y social simultáneo.',
            docs: [{ nombre: 'RS 1 (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/RESPONSABILIDAD%20SOCIAL%20%20%281%29.pdf', disponible: true }] },
        ],
      },
      {
        slug: 'unidad-2', numero: 'II', bubble_label: 'Unidad 2', bubble_title: 'Balance de Materia y Energía',
        titulo: 'Unidad 2 — Balance de Materia y Energía',
        subtitulo: 'Balances industriales, análisis PINCH, caso Vietnam y evaluación grupal',
        num_style: null, orden: 2,
        temas: [
          { label: 'Lectura', titulo: 'Balance de Materia y PML', pill: null, orden: 1,
            descripcion: 'Cerrar balances de forma preventiva reduce residuos y aprovecha mejor la materia prima. Conexión entre eficiencia técnica y prevención ambiental en procesos industriales.',
            docs: [
              { nombre: 'Balance de materia (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Balance%20de%20materia.pdf', disponible: true },
              { nombre: 'Ejercicios (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/cuaderno%20de%20TECNOLOG%C3%8DAS%20LIMPIAS.pdf', disponible: true },
              { nombre: 'Artículo BMyE (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Articulo_BMyE_y_PML.pdf', disponible: true },
            ] },
          { label: 'Caso de estudio', titulo: 'Caso Vietnam', pill: null, orden: 2,
            descripcion: 'Adaptación de conceptos técnicos a condiciones de un país específico. Análisis de datos reales, identificación de brechas y propuesta de mejoras con contexto territorial.',
            docs: [
              { nombre: 'Caso Vietnam (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/caso%20de%20estudio%20vietman.pdf', disponible: true },
              { nombre: 'Taller Cusco-Vietnam (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/CUSCO_VIETNAM.pdf', disponible: true },
            ] },
          { label: 'Análisis energético', titulo: 'Análisis PINCH', pill: null, orden: 3,
            descripcion: 'Herramienta para mapear intercambios térmicos y plantear mejoras concretas en planta. Identificación de oportunidades de ahorro energético. Pilar de procesos industriales sostenibles.',
            docs: [
              { nombre: 'PINCH (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/v26n3e-21114315.pdf', disponible: true },
              { nombre: 'Taller Petroquímico (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Ejercicios%20de%20Balance%20por%20Sector%20Petroqu%C3%ADmico.pdf', disponible: true },
            ] },
          { label: 'IF · Evaluación Grupal U2', titulo: 'Investigación Formativa II + Evaluación Grupal', pill: null, orden: 4,
            descripcion: 'Informes técnicos basados en evidencia. Trabajo en equipo para comunicar recomendaciones técnicas con respaldo cuantitativo de balances de proceso.',
            docs: [
              { nombre: 'IF U2 (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/IF_SEGUNDA_UNIDAD_TECNOLOGIAS_LIMPAS.pdf', disponible: true },
              { nombre: 'Evaluación grupal (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/Examen%20grupal.pdf', disponible: true },
              { nombre: 'RS II (PDF)', url: '/assets/Documentos/apuntes-Tecnologias/RESPONSABILIDAD%20SOCIAL%20%20%281%29_copia%20%281%29.pdf', disponible: true },
            ] },
        ],
      },
      {
        slug: 'unidad-3', numero: 'III', bubble_label: 'Unidad 3', bubble_title: 'Implementación PML y Energía',
        titulo: 'Unidad 3 — Implementación PML y Gestión Energética',
        subtitulo: 'Implementación práctica, factibilidad técnico-económica, ISO 50001 y curtiembre Piel Inka',
        num_style: null, orden: 3,
        temas: [
          { label: 'Implementación', titulo: 'Implementación de un Programa PML', pill: null, orden: 1,
            descripcion: 'Pasos básicos: diagnóstico inicial, identificación de oportunidades, evaluación, aplicación y seguimiento. Requiere compromiso de gerencia y participación activa.',
            docs: [{ nombre: 'Implementación PML (PPTX)', url: '/assets/3%20UNIDAD%2B/Implementacion%20PML%2025.2.pptx', disponible: true }] },
          { label: 'Evaluación técnico-económica', titulo: 'Factibilidad Técnica y Económica', pill: null, orden: 2,
            descripcion: 'Comparación de costos, beneficios y riesgos antes de proponer una intervención ambiental. Análisis de curtiembre como caso de aplicación práctica.',
            docs: [{ nombre: 'Factibilidad (PDF)', url: '/assets/3%20UNIDAD%2B/Factibilidad%20PMLCurtiembre.pdf', disponible: true }] },
          { label: 'Norma nacional', titulo: 'Guía INACAL — PML 2.ª Versión', pill: null, orden: 3,
            descripcion: 'Metodología oficial peruana para implementar un programa PML con buenas prácticas de gestión ambiental adaptadas al contexto nacional.',
            docs: [{ nombre: 'Guía INACAL (PDF)', url: '/assets/3%20UNIDAD%2B/786236592-INACAL-CTN19-SC4-N8-GP-900-200-2021-PRODUCCION-MAS-LIMPIA-Guia-Metodologica-Para-La-Implementacion-de-Un-Programa-de-Produccion-Mas-Limpia-2a-Edicio.pdf', disponible: true }] },
          { label: 'Gestión energética', titulo: 'ISO 50001 y Eficiencia Energética', pill: null, orden: 4,
            descripcion: 'Marco de gestión de la energía para reducir costos y mejorar el desempeño energético de forma continua en distintos sectores económicos.',
            docs: [
              { nombre: 'ISO 50001 (PDF)', url: '/assets/3%20UNIDAD%2B/449015616-ISO-50001-2018-ESP-3.pdf', disponible: true },
              { nombre: 'Mejoras técnicas (PDF)', url: '/assets/3%20UNIDAD%2B/RE-09_Mejoras-tecnicas-sistemas-de-gestion-de-energia-y-lineamiento-EE-en-sectores-economicos.pdf', disponible: true },
            ] },
          { label: 'Caso práctico', titulo: 'Análisis Curtiembre Piel Inka', pill: null, orden: 5,
            descripcion: 'Aplicación práctica de la guía PML 26.1: evaluación de alternativas ambientales, diagrama de flujo del proceso productivo y propuestas de mejora técnica.',
            docs: [
              { nombre: 'Piel Inca (PDF)', url: '/assets/3%20UNIDAD%2B/Curtiembre%20Piel%20Inca_compressed.pdf', disponible: true },
              { nombre: 'Piel Inka (PDF)', url: '/assets/3%20UNIDAD%2B/Piel%20inka.pdf', disponible: true },
            ] },
        ],
      },
      {
        slug: 'laboratorio', numero: 'Lab', bubble_label: 'Laboratorio', bubble_title: 'Prácticas de Proceso',
        titulo: 'Laboratorio — Guías de Prácticas',
        subtitulo: 'Obtención de biodiesel, colorantes naturales, bioplásticos y bio-adsorbentes a partir de recursos andinos y residuos agroindustriales',
        num_style: 'font-size:1.55rem', orden: 4,
        temas: [
          { label: 'Guía 02', titulo: 'Biodiesel como Alternativa Energética Sostenible', pill: null, orden: 1,
            descripcion: 'Obtención de biodiesel mediante transesterificación de aceites vegetales. Evaluación de rendimiento, propiedades fisicoquímicas y potencial de sustitución de combustibles fósiles en el contexto peruano.',
            docs: [{ nombre: 'Guía 02 (PDF)', url: '/assets/Documentos/laboratorio-tecnologias/guia-02-biodiesel.pdf', disponible: true }] },
          { label: 'Guía 03', titulo: 'Extracción de Colorante Natural de Queuña', pill: null, orden: 2,
            descripcion: 'Extracción de pigmentos naturales a partir de Polylepis (queuña), árbol andino. Caracterización del colorante, rendimiento de extracción y posibles aplicaciones en industria textil sostenible.',
            docs: [{ nombre: 'Guía 03 (PDF)', url: '/assets/Documentos/laboratorio-tecnologias/guia-03-colorante-queuna.pdf', disponible: true }] },
          { label: 'Guía 04', titulo: 'Sales de Potasio a partir de Cáscara de Plátano', pill: null, orden: 3,
            descripcion: 'Valorización de residuos agroindustriales: obtención sostenible de sales de potasio a partir de Musa paradisiaca. Cuantificación del rendimiento y evaluación de pureza del producto obtenido.',
            docs: [{ nombre: 'Guía 04 (PDF)', url: '/assets/Documentos/laboratorio-tecnologias/guia-04-sales-potasio-platano.pdf', disponible: true }] },
          { label: 'Guía 05', titulo: 'Bio-adsorbente de Cáscara de Pistacho para Tratamiento de Aguas', pill: null, orden: 4,
            descripcion: 'Preparación y caracterización de bio-adsorbente a partir de cáscara de pistacho. Evaluación de su capacidad de remoción de contaminantes en agua y comparación con carbón activado comercial.',
            docs: [{ nombre: 'Guía 05 (PDF)', url: '/assets/Documentos/laboratorio-tecnologias/guia-05-bioadsorbente-pistacho.pdf', disponible: true }] },
          { label: 'Guía 06', titulo: 'Bioplástico a partir de Cochayuyo', pill: null, orden: 5,
            descripcion: 'Elaboración de bioplástico a base de alga Durvillaea antarctica (cochayuyo). Caracterización mecánica y térmica del material obtenido y evaluación de su biodegradabilidad frente a plásticos convencionales.',
            docs: [{ nombre: 'Guía 06 (PDF)', url: '/assets/Documentos/laboratorio-tecnologias/guia-06-bioplastico-cochayuyo.pdf', disponible: true }] },
          { label: 'Guía 07', titulo: 'Bioplástico a partir de Nostoc commune (Cushuro)', pill: null, orden: 6,
            descripcion: 'Valorización de cianobacterias andinas: obtención de bioplástico a partir de Nostoc commune, conocido localmente como cushuro. Análisis de propiedades, rendimiento y potencial de escalado.',
            docs: [{ nombre: 'Guía 07 (PDF)', url: '/assets/Documentos/laboratorio-tecnologias/guia-07-bioplastico-cushuro.pdf', disponible: true }] },
        ],
      },
      {
        slug: 'salida-campo', numero: 'SC', bubble_label: 'Salida de Campo', bubble_title: 'Visita Técnica Industrial',
        titulo: 'Salida de Campo — Visita Técnica Industrial',
        subtitulo: 'Reconocimiento in situ de procesos productivos, diagnóstico PML y registro de oportunidades de mejora',
        num_style: 'font-size:1.45rem', orden: 5,
        temas: [
          { label: 'Actividad 1 · Reconocimiento', titulo: 'Reconocimiento del Proceso Productivo', pill: null, orden: 1,
            descripcion: 'Recorrido guiado por las instalaciones de la empresa visitada. Identificación de etapas del proceso, equipos clave, puntos de generación de residuos y zonas de alto consumo energético.',
            docs: [{ nombre: 'Ficha de reconocimiento (PDF)', url: '#', disponible: false }] },
          { label: 'Actividad 2 · Diagnóstico', titulo: 'Diagnóstico PML In Situ', pill: null, orden: 2,
            descripcion: 'Aplicación del checklist de diagnóstico PML en planta: evaluación de prácticas de mantenimiento, gestión de insumos, manejo de residuos y uso de agua y energía.',
            docs: [{ nombre: 'Diagnóstico PML (PDF)', url: '#', disponible: false }] },
          { label: 'Actividad 3 · Registro', titulo: 'Registro Fotográfico y de Datos', pill: null, orden: 3,
            descripcion: 'Documentación visual de los puntos críticos del proceso. Toma de datos de consumo energético, generación de efluentes y emisiones para alimentar el balance de materia posterior.',
            docs: [{ nombre: 'Ficha de registro (PDF)', url: '#', disponible: false }] },
          { label: 'IF · Informe Final', titulo: 'Informe Final de Visita Técnica', pill: null, orden: 4,
            descripcion: 'Documento integrador con descripción de la empresa, diagrama de flujo levantado en visita, oportunidades de PML identificadas, evaluación preliminar de viabilidad y recomendaciones.',
            docs: [{ nombre: 'Informe de visita (PDF)', url: '#', disponible: false }] },
        ],
      },
    ],
  },
  {
    slug: 'monitoreo-ambiental', nombre: 'Monitoreo Ambiental', icon: '◑', tiene_unidades: true, orden: 3,
    eyebrow: 'Portafolio de Curso · UAC · 8.º Semestre',
    lead: 'Fundamentos, protocolos y normativa peruana para el monitoreo de la calidad ambiental del agua, aire, ruido y suelo. Docente: Mg. Fiorella E. Díaz Roca.',
    secciones: [
      {
        slug: 'unidad-1', numero: 'I', bubble_label: 'Fundamentos y Agua', bubble_title: 'Fundamentos y Agua',
        titulo: 'Unidad I — Fundamentos del Monitoreo Ambiental y Calidad del Agua',
        subtitulo: 'Bases conceptuales del monitoreo ambiental, normativa ECA y Protocolo Nacional de Monitoreo de Agua',
        num_style: null, orden: 1,
        temas: [
          { label: 'Sesión 1 · Introducción', titulo: 'Introducción al Monitoreo Ambiental', pill: 'Componentes ambientales · ECA', orden: 1,
            descripcion: 'Componentes ambientales sujetos a monitoreo: agua, aire, suelo y ruido. Concepto de monitoreo ambiental (MA) como proceso sistemático de observación, medición y registro de parámetros de calidad. Evaluación de la calidad ambiental y sus alcances regulatorios.',
            docs: [{ nombre: 'Sesión 1 — M.A. (PDF)', url: '/assets/Documentos/textos_de_monitoreo/1/Sesion 1. M.A.pdf', disponible: true }] },
          { label: 'Sesión 2 · Conceptos', titulo: 'Monitoreo vs. Evaluación de la Calidad Ambiental', pill: 'ECA · Protocolos · Guías', orden: 2,
            descripcion: 'Diferencias fundamentales entre monitoreo y evaluación de la calidad ambiental. Guías y protocolos nacionales por componente. Estándares de Calidad Ambiental (ECA) aplicables al agua, aire y suelo como referencia normativa para la interpretación de resultados.',
            docs: [{ nombre: 'Sesión 2 — Monitoreo Ambiental (PDF)', url: '/assets/Documentos/textos_de_monitoreo/1/Sesion 2. Monitoreo Ambiental.pdf', disponible: true }] },
          { label: 'Sesión 3 · Agua', titulo: 'Monitoreo de la Calidad del Agua', pill: 'ECA Agua · Ley 29338 · ANA', orden: 3,
            descripcion: 'Introducción al monitoreo hídrico: parámetros fisicoquímicos y microbiológicos, puntos y frecuencias de muestreo. Normativa ambiental aplicable: ECA para agua (D.S. N.° 004-2017-MINAM) y Ley de Recursos Hídricos N.° 29338. Roles de la ANA y el OEFA.',
            docs: [{ nombre: 'Sesión 3 — M.A. Agua (PDF)', url: '/assets/Documentos/textos_de_monitoreo/1/Sesion 3. M.A. agua.pdf', disponible: true }] },
          { label: 'Sesión 4 · Parte 1', titulo: 'Protocolo Nacional de Monitoreo de Agua — Parte 1', pill: 'Protocolo Nacional · Vertimientos', orden: 4,
            descripcion: 'Protocolo Nacional para el Monitoreo de la Calidad del Agua en cuerpos naturales superficiales: planificación del programa, selección de puntos de muestreo, técnicas de toma de muestra y cadena de custodia. Monitoreo de cuerpos receptores de vertimientos autorizados.',
            docs: [{ nombre: 'Sesión 4 Parte 1 — M.A. Agua (PDF)', url: '/assets/Documentos/textos_de_monitoreo/1/Sesion 4. M.A. AGUA part 1.pdf', disponible: true }] },
          { label: 'Sesión 4 · Parte 2', titulo: 'Protocolo Nacional de Monitoreo de Agua — Parte 2', pill: 'QA/QC · Muestreo · Análisis', orden: 5,
            descripcion: 'Continuación del Protocolo Nacional: preservación y transporte de muestras, equipos de medición in situ (pH-metro, oxímetro, turbidímetro), aseguramiento de la calidad de datos (QA/QC) e interpretación de resultados frente a los ECA por categorías de uso del agua.',
            docs: [{ nombre: 'Sesión 4 Parte 2 — M.A. Agua (PDF)', url: '/assets/Documentos/textos_de_monitoreo/1/Sesion 4. M.A. AGUA part 2.pdf', disponible: true }] },
        ],
      },
      {
        slug: 'unidad-2', numero: 'II', bubble_label: 'Aire y Ruido', bubble_title: 'Aire y Ruido',
        titulo: 'Unidad II — Monitoreo de la Calidad del Aire y Ruido Ambiental',
        subtitulo: 'Evaluación y monitoreo de la calidad del aire, contaminantes atmosféricos, efectos en la salud y Protocolo Nacional',
        num_style: null, orden: 2,
        temas: [
          { label: 'Sesión 1 · Aire', titulo: 'Monitoreo y Evaluación de la Calidad del Aire', pill: 'Contaminantes criterio · ECA Aire', orden: 1,
            descripcion: 'Concepto y características del aire atmosférico. Contaminantes criterio (PM₂.₅, PM₁₀, NO₂, SO₂, CO, O₃) e implicancias en la salud pública y el ambiente. ECA para aire (D.S. N.° 003-2017-MINAM). Red de monitoreo de calidad del aire del SENAMHI y el OEFA.',
            docs: [{ nombre: 'Sesión 1 — M.A. Aire (PDF)', url: '/assets/Documentos/textos_de_monitoreo/2/Sesion 1. M.A. AIRE.pdf', disponible: true }] },
          { label: 'Sesión 2 · Protocolo', titulo: 'Protocolo Nacional de Monitoreo de Calidad del Aire', pill: 'Protocolo Nacional · Estaciones · QA/QC', orden: 2,
            descripcion: 'Protocolo Nacional para el monitoreo de la calidad ambiental del aire: criterios de ubicación de estaciones, métodos de referencia aprobados, equipos de muestreo activo y pasivo, frecuencia de muestreo y gestión de datos. Garantía y control de calidad (QA/QC) en redes de monitoreo.',
            docs: [{ nombre: 'Sesión 2 — Protocolo de Aire (PDF)', url: '/assets/Documentos/textos_de_monitoreo/2/Sesion 2. PROTOCOLO DE AIRE.pdf', disponible: true }] },
          { label: 'Sesión 3 · Ruido (1.ª parte)', titulo: 'Monitoreo de Calidad de Ruido — Introducción', pill: 'Acústica ambiental · NPS · Leq', orden: 3,
            descripcion: 'Diferencia entre sonido y ruido. Problemática ambiental del ruido urbano e industrial. Parámetros acústicos: nivel de presión sonora (NPS), nivel equivalente continuo (Leq), dosis de ruido. Efectos del ruido en la salud: pérdida auditiva, estrés, trastornos del sueño.',
            docs: [{ nombre: 'Sesión 3 — M.A. Ruido 1.ª parte (PDF)', url: '/assets/Documentos/textos_de_monitoreo/2/Sesion 3. M.A. RUIDO 1ra parte.pdf', disponible: true }] },
        ],
      },
      {
        slug: 'unidad-3', numero: 'III', bubble_label: 'Ruido, Suelo y Plan', bubble_title: 'Ruido, Suelo y Plan',
        titulo: 'Unidad III — Normativa de Ruido, Monitoreo de Suelos y Plan de Monitoreo',
        subtitulo: 'Normativa peruana de ruido (ECA D.S. 085-2003-PCM y NTP), monitoreo de la calidad del suelo y elaboración de Plan de Monitoreo',
        num_style: null, orden: 3,
        temas: [
          { label: 'Sesión 3 · Ruido (2.ª parte)', titulo: 'Normativa Aplicable al Monitoreo de Ruido', pill: 'D.S. 085-2003-PCM · ECA Ruido · OEFA', orden: 1,
            descripcion: 'Marco normativo peruano para el ruido ambiental: ECA para ruido aprobado mediante D.S. N.° 085-2003-PCM. Zonas de aplicación (residencial, comercial, industrial, especial) y sus valores límite diurnos y nocturnos. Procedimiento de medición, equipos (sonómetros clase 1 y 2) y reporte de resultados al OEFA.',
            docs: [{ nombre: 'Sesión 3 — M.A. Ruido 2.ª parte (PDF)', url: '/assets/Documentos/textos_de_monitoreo/3/Sesion 3. M.A. RUIDO 2da parte.pdf', disponible: true }] },
          { label: 'Sesión 3 · Protocolo NTP', titulo: 'Protocolo de Ruido y Norma Técnica Peruana', pill: 'NTP · Protocolo de medición', orden: 2,
            descripcion: 'Análisis del ECA para Ruido en el Perú. La Norma Técnica Peruana (NTP) como complemento procedimental al D.S. 085-2003-PCM: metodología de medición, selección y ubicación de puntos de monitoreo, condiciones meteorológicas admisibles y correcciones por tonalidad e impulsividad.',
            docs: [{ nombre: 'Sesión 3 — Protocolo de Ruido y NTP (PDF)', url: '/assets/Documentos/textos_de_monitoreo/3/Sesion 3. Protocolo de ruido y NTP.pdf', disponible: true }] },
          { label: 'Sesión 4 · Suelo (Parte 1)', titulo: 'Monitoreo de la Calidad del Suelo — Parte 1', pill: 'ECA Suelo · Metales pesados · Muestreo', orden: 3,
            descripcion: 'Fundamentos del monitoreo de suelos: clasificación de suelos, parámetros de calidad (metales pesados, hidrocarburos totales, pesticidas organoclorados), Estándares de Calidad Ambiental para Suelo (D.S. N.° 002-2013-MINAM) y procedimientos de toma de muestra superficial y profunda.',
            docs: [{ nombre: 'Sesión 4 Parte 1 — M.A. Suelo (PDF)', url: '/assets/Documentos/textos_de_monitoreo/3/Sesion 4. M.A. SUELO part 1.pdf', disponible: true }] },
          { label: 'Sesión 4 · Suelo (Parte 2)', titulo: 'Monitoreo de la Calidad del Suelo — Parte 2', pill: 'Puntos de muestreo · Calicatas · Lab. acreditado', orden: 4,
            descripcion: 'Determinación de puntos de muestreo mediante rejillas, transectos y criterios de representatividad espacial. Técnicas de excavación, uso de calicatas y barrenos. Análisis de laboratorio acreditado, interpretación de resultados e identificación de suelos contaminados.',
            docs: [{ nombre: 'Sesión 4 Parte 2 — M.A. Suelo (PDF)', url: '/assets/Documentos/textos_de_monitoreo/3/Sesion 4. M.A. SUELO part 2.pdf', disponible: true }] },
          { label: 'Actividad integradora', titulo: 'Elaboración de un Plan de Monitoreo Ambiental', pill: 'Plan de Monitoreo · Documento integrador', orden: 5,
            descripcion: 'Guía para la elaboración integral de un Plan de Monitoreo de Calidad Ambiental abarcando agua, aire, ruido y suelo. Estructura del plan: introducción, objetivos, zona de muestreo, parámetros a monitorear, frecuencia, métodos de análisis, cadena de custodia, reportes y plan de contingencia.',
            docs: [{ nombre: 'Actividad — Plan de Monitoreo (PDF)', url: '/assets/Documentos/textos_de_monitoreo/3/A. ELABORAR UN PLAN DE MONITOREO DE CALIDAD DE.pdf', disponible: true }] },
        ],
      },
    ],
  },
  {
    slug: 'riesgos-ambientales', nombre: 'Riesgos Ambientales', icon: '◉', tiene_unidades: false, orden: 4,
    eyebrow: 'Portafolio de Curso · UAC',
    lead: 'Identificación, evaluación cuantitativa y cualitativa de riesgos, mapas de riesgo con ArcGIS y planes de manejo ambiental.',
    secciones: [
      {
        slug: 'contenido', numero: '·', bubble_label: 'Contenido', bubble_title: 'Temas del Curso',
        titulo: 'Temas del Curso',
        subtitulo: '',
        num_style: null, orden: 1,
        temas: [
          { label: 'Tema 1', titulo: 'Identificación de Riesgos Ambientales', pill: null, orden: 1,
            descripcion: 'Metodologías para la identificación sistemática de peligros ambientales. Matrices de identificación, registros de aspectos e impactos, y listas de verificación para distintos tipos de actividades industriales y naturales.',
            docs: [] },
          { label: 'Tema 2', titulo: 'Evaluación Cuantitativa de Riesgos', pill: null, orden: 2,
            descripcion: 'Métodos probabilísticos para cuantificar la magnitud del riesgo. Análisis de frecuencias, consecuencias y matrices de riesgo. Valores límites y umbrales de aceptabilidad en normativa peruana e internacional.',
            docs: [] },
          { label: 'Tema 3', titulo: 'Evaluación Cualitativa de Riesgos', pill: null, orden: 3,
            descripcion: 'Herramientas de análisis cualitativo: HAZOP, What-If Analysis y árboles de falla. Priorización de riesgos mediante matrices de probabilidad-severidad y criterios de gestión adaptados al sector ambiental.',
            docs: [] },
          { label: 'Tema 4 · SIG', titulo: 'Mapas de Riesgo con ArcGIS', pill: null, orden: 4,
            descripcion: 'Elaboración de cartografía de riesgo ambiental mediante sistemas de información geográfica. Integración de capas de amenaza, vulnerabilidad y exposición para generar índices espaciales de riesgo.',
            docs: [] },
          { label: 'Tema 5', titulo: 'Planes de Manejo Ambiental', pill: null, orden: 5,
            descripcion: 'Estructura y contenido de un Plan de Manejo Ambiental (PMA): medidas de prevención, mitigación, corrección y compensación. Diseño de programas de monitoreo y seguimiento ambiental post-medida.',
            docs: [] },
          { label: 'Tema 6 · Sector', titulo: 'Riesgos en la Industria Extractiva', pill: null, orden: 6,
            descripcion: 'Evaluación de riesgos específicos de minería e hidrocarburos: derrames, subsidencias, pasivos ambientales y contaminación hídrica. Marco normativo peruano de la certificación ambiental (EIA/SEIA).',
            docs: [] },
          { label: 'Evidencias', titulo: 'Trabajos y Evidencias del Curso', pill: null, orden: 7,
            descripcion: 'Recopilación de los trabajos prácticos desarrollados durante el semestre: mapas temáticos, informes de evaluación de riesgos y planes de manejo elaborados en la asignatura.',
            docs: [] },
        ],
      },
    ],
  },
  {
    slug: 'topicos-pml', nombre: 'Tópicos de PML', icon: '◎', tiene_unidades: false, orden: 5,
    eyebrow: 'Portafolio de Curso · UAC',
    lead: 'Profundización conceptual y aplicada en PML: principios, herramientas de diagnóstico, normativa peruana e internacional y casos de implementación industrial.',
    secciones: [
      {
        slug: 'contenido', numero: '·', bubble_label: 'Contenido', bubble_title: 'Temas del Curso',
        titulo: 'Temas del Curso',
        subtitulo: '',
        num_style: null, orden: 1,
        temas: [
          { label: 'Tema 1', titulo: 'Concepto de Producción Más Limpia', pill: 'Estrategia preventiva', orden: 1,
            descripcion: 'La PML es una estrategia ambiental preventiva que busca reducir los impactos negativos desde el origen del proceso productivo. A diferencia de los enfoques tradicionales centrados en el tratamiento de residuos, la PML actúa antes de que estos se generen.',
            docs: [] },
          { label: 'Tema 2', titulo: 'Principios Fundamentales de la PML', pill: 'Prevención · Eficiencia', orden: 2,
            descripcion: 'Los principios se centran en la prevención, la eficiencia y la sustitución de insumos peligrosos. La prevención implica anticiparse a los problemas antes de que ocurran; la eficiencia busca optimizar el uso de recursos reduciendo costos y emisiones simultáneamente.',
            docs: [] },
          { label: 'Tema 3', titulo: 'Beneficios Ambientales y Económicos', pill: 'Doble dividendo', orden: 3,
            descripcion: 'La PML ofrece beneficios ambientales claros: reducción de emisiones contaminantes y disminución de residuos sólidos. En el plano económico, las empresas que aplican PML reducen costos operativos gracias al menor consumo de recursos y al aprovechamiento de subproductos.',
            docs: [] },
          { label: 'Tema 4', titulo: 'Herramientas y Técnicas de PML', pill: 'Diagnóstico · Auditoría', orden: 4,
            descripcion: 'Entre las herramientas más utilizadas se encuentran las auditorías ambientales y los diagnósticos de procesos, que permiten identificar oportunidades de mejora. Incluye rediseño de productos, buenas prácticas operativas y mantenimiento preventivo.',
            docs: [] },
          { label: 'Tema 5', titulo: 'Implementación en la Industria', pill: 'Ciclo de mejora continua', orden: 5,
            descripcion: 'La implementación sigue un proceso estructurado: diagnóstico inicial, identificación de oportunidades, evaluación técnica y económica, aplicación de medidas y seguimiento de resultados. Requiere compromiso de la gerencia y participación activa de los trabajadores.',
            docs: [] },
          { label: 'Tema 6 · Norma', titulo: 'ISO 10628 — Diagramas de Proceso', pill: 'PFDs · P&IDs', orden: 6,
            descripcion: 'Norma internacional que establece las reglas para la elaboración de PFDs y P&IDs en ingeniería química e industrial. Su aplicación en PML facilita la identificación de puntos críticos dentro de procesos productivos y la comunicación técnica precisa entre equipos.',
            docs: [] },
          { label: 'Tema 7', titulo: 'Aplicaciones Sectoriales', pill: 'Casos reales', orden: 7,
            descripcion: 'Casos de aplicación de PML en industrias de alto impacto ambiental: textil, curtiembre, petroquímica y manufactura metálica. Comparación de indicadores antes y después de la implementación de medidas preventivas.',
            docs: [] },
          { label: 'Tema 8', titulo: 'Manejo de Sustancias Peligrosas', pill: 'GHS · Sustitución', orden: 8,
            descripcion: 'Inventario, etiquetado y almacenamiento de sustancias peligrosas bajo criterios GHS y la normativa peruana. Sustitución de insumos peligrosos como medida clave de producción más limpia en el sector industrial.',
            docs: [] },
          { label: 'Tema 9', titulo: 'Casos Prácticos — Cusco', pill: 'Contexto local', orden: 9,
            descripcion: 'Análisis de casos locales con potencial de aplicación PML en la región Cusco. Identificación de sectores prioritarios: agroindustria, curtiembre artesanal y pequeña minería. Propuestas adaptadas al contexto andino.',
            docs: [] },
          { label: 'Tema 10 · Cierre', titulo: 'PML como Eje de la Ingeniería Ambiental', pill: 'Síntesis', orden: 10,
            descripcion: 'La producción más limpia no es un conjunto de técnicas aisladas, sino una filosofía de gestión que integra la prevención ambiental con la competitividad industrial. Su adopción es indispensable para la transición hacia economías más sostenibles en el contexto peruano.',
            docs: [] },
        ],
      },
    ],
  },
];
